### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by JaimeSierra** [diomed/DarkBlue4Brackets#2]
Hi,

The screenshot is amazing, but install and not view. I using Brackets Release 1.10 versión 1.10.0-17483 (release 024bee940). Please help me.

Regards,

Jaime

**Comment by diomed** [comment]
hmmm... 

I wish I could help you.
Did you selecting it from View - Themes...
Or reloading Brackets?

I run exactly the same Brackets version and it displays normally for me.

**Comment by JaimeSierra** [comment]
Hi,

Very thanks for your help, but are the letters in white? What should be done to make them look blue?

![captura de pantalla 2017-09-05 a las 7 41 15 a m](https://user-images.githubusercontent.com/17964090/30057780-85fdf3cc-920e-11e7-80b5-c6e88f9c2027.png)

**Comment by diomed** [comment]
yes, letters are in white, coz if they'd be blue u wouldn't really recognize what is what.
That being said, u can go to :

C:\Users\...\AppData\Roaming\Brackets\extensions\user\dark-blue

file called **main.less**

and find this line right in the beginning:
@foreground: #fafara; // Code foreground

and change it to whatever hex color you like.

**Comment by JaimeSierra** [comment]
Very thanks, fantastic!!!

Regards,


Jaime
